site_name: VarTester

theme:
  name: material
  palette:
    scheme: default

nav:
  - Home: index.md
  - VarTester: vartester.md
  - Model Monitoring: model_monitoring.md

plugins: 
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            heading_level: 3

use_directory_urls: true
