# Data preparation parameters
data_preparation:
  feature_columns:
    - age
    - income
    - credit_score
  target_column: target_B  # Change this to target_A, target_B, target_C, or any other target column

# Model training parameters
model_training:
  # Data splitting
  test_size: 0.2
  random_state: 42
  
  # CatBoost model parameters
  loss_function: "Poisson"  # Default Poisson loss for count data
  iterations: 1000
  learning_rate: 0.1
  depth: 6
  early_stopping_rounds: 100
  verbose: 100

# Model validation parameters
model_validation:
  # Column mappings
  target_column: target_B
  prediction_column: prediction_new
  weight_column: weight
  old_model_column: prediction_A  # Optional: column name for old model predictions for comparison
  
  # MLflow settings
  use_mlflow: true  # Whether to use MLflow for model loading and artifact storage
  
  # Feature segmentation settings
  feature_binning:
    # Default binning strategy for all features (if not specified individually)
    default_bins: 5  # Number of quantile-based bins
    
    # Custom binning for specific features
    age:  # Keep original age binning as example
      bins: [18, 30, 45, 60, 75]
      labels: ["18-29", "30-44", "45-59", "60+"]
    
    credit_score:  # Example: custom bins for credit score
      bins: [300, 550, 650, 750, 850]
      labels: ["Poor", "Fair", "Good", "Excellent"]
    # 
    # income:  # Example: use 4 quantile bins for income
    #   bins: 4
  
  # Analysis settings
  bootstrap: false  # Whether to use bootstrap for confidence intervals
  old_model_noise_factor: 0.1  # Noise factor for synthetic old model generation
  
  # Reporting settings
  plot_theme:
    annotation_fontsize: 14
    style: "ggplot"
    target_color: "#1E1D25"
    h_line_style: ":"

# Examples for different targets:
# For target_A: change target_column to "target_A"
# For target_B: change target_column to "target_B" 
# For target_C: change target_column to "target_C"
# For any custom target: change target_column to your desired column name
